# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.16
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.16"
    - name: Install dependencies
      run: |
        apt-get install -y curl ffmpeg libsm6 libxext6
        curl -sSL https://install.python-poetry.org | python3.9 -
        export PATH="$HOME/.local/bin:${PATH}"
        poetry install

    - name: Copy files
      run: |
        cp ./pyproject_backend.toml $HOME/pyproject.toml
        cp ./poetry.lock $HOME/poetry.lock
        cp -r ./assets/filters $HOME/assets/filters
        cp -r ./assets/misc $HOME/assets/misc
        cp -r ./config $HOME/config
        cp -r ./googly_eyes/backend $HOME/googly_eyes/backend
        cp -r ./tests/backend $HOME/tests/backend

    - name: Run unit tests
      run: |
        cd $HOME
        poetry run python -m unittest discover tests/backend
