# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Googly Eyes CI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.16
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.16"
        
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        ls -lah
        sudo apt-get install -y curl ffmpeg libsm6 libxext6
        curl -sSL https://install.python-poetry.org | python3.9 -
        export PATH="$HOME/.local/bin:${PATH}"
        poetry install
        poetry add coverage
        poetry check
        
    - name: Run backend and frontend unit tests
      run: |
        poetry run coverage run -m unittest discover -s tests --pattern=test_*.py --omit='*/performance/*'
        poetry run coverage html -i --omit="*/tests/*"
        poetry run coverage report -m -i --omit="*/tests/*"
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v1
      with:
        name: "html_coverage_report"
        path: htmlcov

